CREATE TABLE IF NOT EXISTS sellers (
  seller_id text PRIMARY KEY,
  seller_zip_code_prefix integer,
  seller_city text,
  seller_state text
);
CREATE INDEX IF NOT EXISTS idx_sellers_zip ON sellers (seller_zip_code_prefix);

CREATE TABLE IF NOT EXISTS customers (
  customer_id text PRIMARY KEY,
  customer_unique_id text NOT NULL,
  customer_zip_code_prefix integer,
  customer_city text,
  customer_state text
);
CREATE INDEX IF NOT EXISTS idx_customers_unique_id ON customers (customer_unique_id);
CREATE INDEX IF NOT EXISTS idx_customers_zip ON customers (customer_zip_code_prefix);

CREATE TABLE IF NOT EXISTS geolocation (
  geolocation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  geolocation_zip_code_prefix integer,
  geolocation_lat double precision,
  geolocation_lng double precision,
  geolocation_city text,
  geolocation_state text
);
CREATE INDEX IF NOT EXISTS idx_geolocation_zip ON geolocation (geolocation_zip_code_prefix);
CREATE INDEX IF NOT EXISTS idx_geolocation_city_state ON geolocation (geolocation_city, geolocation_state);

CREATE TABLE IF NOT EXISTS leads_qualified (
  mql_id text PRIMARY KEY,
  first_contact_date timestamp,
  landing_page_id text,
  origin text
);
CREATE INDEX IF NOT EXISTS idx_leads_first_contact ON leads_qualified (first_contact_date);

CREATE TABLE IF NOT EXISTS product_category_name_translation (
  product_category_name text PRIMARY KEY,
  product_category_name_english text
);

CREATE TABLE IF NOT EXISTS products (
  product_id text PRIMARY KEY,
  product_category_name text,
  product_name_lenght integer,
  product_description_lenght integer,
  product_photos_qty integer,
  product_weight_g numeric,
  product_length_cm numeric,
  product_height_cm numeric,
  product_width_cm numeric,
  CONSTRAINT fk_products_category FOREIGN KEY (product_category_name)
    REFERENCES product_category_name_translation(product_category_name)
    ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_products_category ON products (product_category_name);

CREATE TABLE IF NOT EXISTS orders (
  order_id text PRIMARY KEY,
  customer_id text NOT NULL,
  order_status text,
  order_purchase_timestamp timestamp,
  order_approved_at timestamp,
  order_delivered_carrier_date timestamp,
  order_delivered_customer_date timestamp,
  order_estimated_delivery_date timestamp,
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders (customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_purchase_ts ON orders (order_purchase_timestamp);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (order_status);

CREATE TABLE IF NOT EXISTS order_reviews (
  review_row_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id text NOT NULL,
  order_id text NOT NULL,
  review_score integer,
  review_comment_title text,
  review_comment_message text,
  review_creation_date timestamp,
  review_answer_timestamp timestamp,
  CONSTRAINT fk_order_reviews_order FOREIGN KEY (order_id)
    REFERENCES orders(order_id)
    ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_orderreviews_order ON order_reviews (order_id);
CREATE INDEX IF NOT EXISTS idx_orderreviews_score ON order_reviews (review_score);

CREATE TABLE IF NOT EXISTS order_payments (
  order_id text NOT NULL,
  payment_sequential integer NOT NULL,
  payment_type text,
  payment_installments integer,
  payment_value numeric,
  PRIMARY KEY (order_id, payment_sequential),
  CONSTRAINT fk_order_payments_order FOREIGN KEY (order_id)
    REFERENCES orders(order_id)
    ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_orderpayments_order ON order_payments (order_id);
CREATE INDEX IF NOT EXISTS idx_orderpayments_type ON order_payments (payment_type);

CREATE TABLE IF NOT EXISTS leads_closed (
  mql_id text PRIMARY KEY,
  seller_id text,
  sdr_id text,
  sr_id text,
  won_date timestamp,
  business_segment text,
  lead_type text,
  lead_behaviour_profile text,
  has_company text,
  has_gtin text,
  average_stock text,
  business_type text,
  declared_product_catalog_size numeric,
  declared_monthly_revenue numeric,
  CONSTRAINT fk_leads_closed_mql FOREIGN KEY (mql_id)
    REFERENCES leads_qualified(mql_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_leads_closed_seller FOREIGN KEY (seller_id)
    REFERENCES sellers(seller_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_leads_won_date ON leads_closed (won_date);
CREATE INDEX IF NOT EXISTS idx_leads_seller ON leads_closed (seller_id);

CREATE TABLE IF NOT EXISTS order_items (
  order_id text NOT NULL,
  order_item_id integer NOT NULL,
  product_id text,
  seller_id text,
  shipping_limit_date timestamp,
  price numeric,
  freight_value numeric,
  PRIMARY KEY (order_id, order_item_id),
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
    REFERENCES orders(order_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_order_items_product FOREIGN KEY (product_id)
    REFERENCES products(product_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_order_items_seller FOREIGN KEY (seller_id)
    REFERENCES sellers(seller_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_orderitems_product ON order_items (product_id);
CREATE INDEX IF NOT EXISTS idx_orderitems_seller ON order_items (seller_id);
CREATE INDEX IF NOT EXISTS idx_orderitems_order ON order_items (order_id);
