from pathlib import Path
import json
from config import ROOT
from terminology import transform, replace_technical
DB=ROOT/'База_данных';DB.mkdir(parents=True,exist_ok=True)
tables=[]
def col(name,typ,rule='',meaning='',ref=None):return dict(name=name,type=typ,rule=rule,meaning=meaning,ref=ref)
def ident(name='id'):return col(name,'bigint','GENERATED ALWAYS AS IDENTITY PRIMARY KEY','Идентификатор')
def fk(name,table,nullable=False):return col(name,'bigint',('' if nullable else 'NOT NULL ')+f'REFERENCES {table}(id)', 'Ссылка на '+table,table)
def txt(name,size=120,rule='NOT NULL',meaning=''):return col(name,f'varchar({size})',rule,meaning)
def ts(name='created_at',nullable=False):return col(name,'timestamptz','' if nullable else 'NOT NULL DEFAULT CURRENT_TIMESTAMP','Момент времени')
def tab(name,title,cols,extra=[],group=1):tables.append(dict(name=name,title=title,columns=cols,constraints=extra,group=group))
tab('role','Роль',[txt('code',16,'PRIMARY KEY'),txt('name',80)],group=3)
tab('app_user','Пользователь',[ident(),txt('login',80,'NOT NULL UNIQUE'),txt('password_hash',255),txt('display_name'),col('active','boolean','NOT NULL DEFAULT true'),ts()],group=3)
tab('user_role','Назначение роли',[fk('user_id','app_user'),txt('role_code',16,'NOT NULL REFERENCES role(code)'),ts()],['PRIMARY KEY (user_id, role_code)'],3)
tab('supplier','Поставщик',[ident(),txt('code',16,'NOT NULL UNIQUE'),txt('name'),col('priority','smallint','NOT NULL CHECK (priority > 0)'),col('enabled','boolean','NOT NULL DEFAULT true')])
tab('component','Компонент',[ident(),txt('code',20,'NOT NULL UNIQUE'),txt('kind',12,"NOT NULL CHECK (kind IN ('CASE','CPU','BOARD','RAM','GPU','SSD','PSU','COOLER'))"),txt('model',150),col('mass_kg','numeric(8,3)','NOT NULL CHECK (mass_kg > 0)'),col('active','boolean','NOT NULL DEFAULT true')])
tab('characteristic','Характеристика',[ident(),txt('code',32,'NOT NULL UNIQUE'),txt('name'),txt('value_kind',8,"NOT NULL CHECK (value_kind IN ('NUMBER','TEXT'))"),txt('unit',16,'')])
tab('component_value','Значение характеристики',[fk('component_id','component'),fk('characteristic_id','characteristic'),col('number_value','numeric(14,4)'),txt('text_value',150,'')],['PRIMARY KEY (component_id, characteristic_id)','CHECK ((number_value IS NULL) <> (text_value IS NULL))'])
tab('component_group','Группа компонентов',[ident(),txt('code',32,'NOT NULL UNIQUE'),txt('name'),txt('kind',12),col('criteria','jsonb',"NOT NULL CHECK (jsonb_typeof(criteria) = 'object')",'Предикат по кодам характеристик')])
tab('supplier_product','Товар поставщика',[ident(),fk('supplier_id','supplier'),txt('external_sku',80),txt('title',180),fk('component_id','component',True),col('active','boolean','NOT NULL DEFAULT true')],['UNIQUE (supplier_id, external_sku)'])
tab('supplier_offer','Предложение поставщика',[ident(),fk('product_id','supplier_product'),col('price','numeric(14,2)','NOT NULL CHECK (price > 0)'),txt('currency',3,"NOT NULL DEFAULT 'RUB' CHECK (currency = 'RUB')"),col('available_qty','integer','NOT NULL CHECK (available_qty >= 0)'),ts('observed_at'),txt('source_hash',64)],['UNIQUE (product_id, observed_at, source_hash)'])
tab('bom','BOM',[ident(),txt('code',24,'NOT NULL UNIQUE'),txt('name',150),fk('created_by','app_user'),ts()],group=2)
tab('change_request','Запрос на изменение',[ident(),fk('bom_id','bom'),fk('created_by','app_user'),txt('kind',12,"NOT NULL CHECK (kind IN ('CREATE','UPDATE','REPLACE'))"),col('reason','text','NOT NULL'),ts()],group=2)
tab('bom_version','Версия BOM',[ident(),fk('bom_id','bom'),col('version_no','integer','NOT NULL CHECK (version_no > 0)'),fk('request_id','change_request'),fk('case_component_id','component'),txt('state',12,"NOT NULL CHECK (state IN ('DRAFT','CHECKED','ARCHIVED'))"),fk('created_by','app_user'),ts()],['UNIQUE (bom_id, version_no)'],2)
tab('bom_slot','Слот BOM',[ident(),fk('version_id','bom_version'),txt('slot_code',20),col('quantity','integer','NOT NULL CHECK (quantity > 0)'),fk('component_id','component',True),fk('group_id','component_group',True),fk('pinned_product_id','supplier_product',True)],['UNIQUE (version_id, slot_code)','CHECK ((component_id IS NULL) <> (group_id IS NULL))','CHECK (pinned_product_id IS NULL OR component_id IS NOT NULL)'],2)
tab('slot_selection','Разрешённый слот',[col('slot_id','bigint','PRIMARY KEY REFERENCES bom_slot(id)','Слот','bom_slot'),fk('offer_id','supplier_offer'),fk('resolved_component_id','component'),ts('selected_at')],group=2)
tab('compatibility_rule','Правило совместимости',[ident(),txt('code',32),col('revision','integer','NOT NULL CHECK (revision > 0)'),txt('name',150),col('expression','jsonb','NOT NULL'),col('enabled','boolean','NOT NULL DEFAULT true')],['UNIQUE (code, revision)'],2)
tab('validation_result','Результат проверки',[ident(),fk('version_id','bom_version'),col('valid','boolean','NOT NULL'),col('rules_snapshot','jsonb','NOT NULL'),col('issues','jsonb',"NOT NULL DEFAULT '[]'::jsonb"),ts('checked_at')],group=2)
tab('replacement_rule','Правило замены',[ident(),txt('code',32,'NOT NULL UNIQUE'),fk('from_component_id','component'),fk('to_component_id','component'),fk('from_product_id','supplier_product',True),fk('to_product_id','supplier_product',True),col('scope','jsonb',"NOT NULL DEFAULT '{}'::jsonb"),col('enabled','boolean','NOT NULL DEFAULT true')],['CHECK (from_component_id <> to_component_id OR from_product_id IS DISTINCT FROM to_product_id)'],2)
tab('replacement_batch','Пакет массовой замены',[ident(),fk('rule_id','replacement_rule'),fk('created_by','app_user'),txt('state',12,"NOT NULL CHECK (state IN ('PREVIEW','RUNNING','DONE','PARTIAL','CANCELLED'))"),col('rule_snapshot','jsonb','NOT NULL'),ts()],group=2)
tab('replacement_item','Результат замены BOM',[fk('batch_id','replacement_batch'),fk('bom_id','bom'),fk('old_version_id','bom_version'),fk('new_version_id','bom_version',True),txt('result',12,"NOT NULL CHECK (result IN ('PENDING','APPLIED','CONFLICT','SKIPPED'))"),col('details','jsonb',"NOT NULL DEFAULT '{}'::jsonb")],['PRIMARY KEY (batch_id, bom_id)'],2)
tab('calculation_rule','Правило цены и веса',[ident(),txt('code',24),col('revision','integer','NOT NULL CHECK (revision > 0)'),col('markup_rate','numeric(6,4)','NOT NULL CHECK (markup_rate >= 0)'),col('assembly_cost','numeric(12,2)','NOT NULL CHECK (assembly_cost >= 0)'),col('packaging_cost','numeric(12,2)','NOT NULL CHECK (packaging_cost >= 0)'),col('packaging_mass','numeric(8,3)','NOT NULL CHECK (packaging_mass >= 0)'),col('round_step','numeric(8,2)','NOT NULL CHECK (round_step > 0)'),col('offer_ttl_hours','integer','NOT NULL CHECK (offer_ttl_hours > 0)')],['UNIQUE (code, revision)'],3)
tab('card','Карточка товара',[ident(),fk('bom_id','bom'),txt('offer_id',64,'NOT NULL UNIQUE'),txt('status',20,"NOT NULL CHECK (status IN ('DRAFT','REVIEW','READY','PUBLISHED','STALE','PUBLISH_ERROR'))"),fk('responsible_id','app_user'),ts()],group=3)
tab('card_version','Версия карточки',[ident(),fk('card_id','card'),col('version_no','integer','NOT NULL CHECK (version_no > 0)'),fk('bom_version_id','bom_version'),fk('validation_id','validation_result'),fk('calculation_rule_id','calculation_rule'),txt('title',200),col('description','text','NOT NULL'),col('attributes','jsonb','NOT NULL'),col('cost','numeric(14,2)','NOT NULL CHECK (cost > 0)'),col('price','numeric(14,2)','NOT NULL CHECK (price > 0)'),col('mass_kg','numeric(8,3)','NOT NULL CHECK (mass_kg > 0)'),col('calculation_snapshot','jsonb','NOT NULL'),ts()],['UNIQUE (card_id, version_no)'],3)
tab('image_template','Шаблон изображения',[ident(),txt('code',32),col('revision','integer','NOT NULL CHECK (revision > 0)'),txt('storage_key',255),col('approved','boolean','NOT NULL DEFAULT false')],['UNIQUE (code, revision)'],3)
tab('image_asset','Изображение',[ident(),fk('template_id','image_template',True),txt('storage_key',255,'NOT NULL UNIQUE'),txt('sha256',64),col('width_px','integer','NOT NULL CHECK (width_px > 0)'),col('height_px','integer','NOT NULL CHECK (height_px > 0)'),fk('created_by','app_user'),ts()],group=3)
tab('card_image','Изображения версии карточки',[fk('card_version_id','card_version'),fk('image_id','image_asset'),col('position','smallint','NOT NULL CHECK (position > 0)')],['PRIMARY KEY (card_version_id, image_id)','UNIQUE (card_version_id, position)'],3)
tab('publication','Публикация и очередь',[ident(),fk('card_version_id','card_version'),txt('operation_key',64,'NOT NULL UNIQUE'),txt('external_task_id',100,''),txt('external_product_id',100,''),txt('state',16,"NOT NULL CHECK (state IN ('QUEUED','SENDING','WAITING','RETRY','SUCCESS','FAILED','UNCERTAIN'))"),col('retry_count','smallint','NOT NULL DEFAULT 0 CHECK (retry_count BETWEEN 0 AND 3)'),ts('next_attempt_at',True),col('request_snapshot','jsonb','NOT NULL'),col('response','jsonb'),txt('error_code',80,''),ts(),ts('completed_at',True)],group=3)
tab('audit_event','Событие аудита',[ident(),fk('actor_id','app_user',True),txt('actor_kind',12,"NOT NULL CHECK (actor_kind IN ('USER','SERVICE'))"),txt('resource_type',40),txt('resource_key',100),txt('action',40),col('before_data','jsonb'),col('after_data','jsonb'),ts()],group=3)
tab('notification','Уведомление',[ident(),fk('recipient_id','app_user'),fk('card_id','card',True),txt('kind',32),col('message','text','NOT NULL'),ts(),ts('read_at',True)],group=3)
indexes=[('ix_offer_latest','supplier_offer','product_id, observed_at DESC'),('ix_product_component','supplier_product','component_id'),('ix_bom_case','bom_version','case_component_id'),('ix_slot_component','bom_slot','component_id'),('ix_slot_group','bom_slot','group_id'),('ix_slot_product','bom_slot','pinned_product_id'),('ix_card_status','card','status, responsible_id'),('ix_publication_due','publication','state, next_attempt_at'),('ix_audit_time','audit_event','created_at'),('ix_notification_user','notification','recipient_id, read_at')]
tables=transform(tables)
indexes=[tuple(replace_technical(value) for value in index) for index in indexes]
for table_name,prefix in [('model_line','MR'),('component','CMP'),('card','UCOMS')]:
 field='offer_id' if table_name=='card' else 'code'
 next(c for t in tables if t['name']==table_name for c in t['columns'] if c['name']==field)['rule']+=f" DEFAULT ('{prefix}-' || lpad(nextval('{table_name}_code_seq')::text, 6, '0'))"
ddl=['-- Учебный проект РОП. PostgreSQL 18. Кодировка UTF8.','-- Создание в отдельной пустой схеме. Исторические версии не удаляются.','BEGIN;','CREATE SCHEMA IF NOT EXISTS rop;','SET search_path TO rop, public;']
ddl += [f'CREATE SEQUENCE {name}_code_seq MINVALUE 1 MAXVALUE 999999 NO CYCLE;' for name in ['model_line','component','card']]
for t in tables:
 fields=[f"  {c['name']} {c['type']} {c['rule']}".rstrip() for c in t['columns']]+['  '+x for x in t['constraints']]
 ddl.append(f"CREATE TABLE {t['name']} (\n"+',\n'.join(fields)+'\n);')
 ddl.append(f"COMMENT ON TABLE {t['name']} IS '{t['title']}';")
for name,table,fields in indexes:ddl.append(f'CREATE INDEX {name} ON {table} ({fields});')
ddl+=['CREATE UNIQUE INDEX ux_publication_active_version ON publication(card_version_id) WHERE state NOT IN (\'SUCCESS\',\'FAILED\');',"INSERT INTO role(code,name) VALUES ('MANAGER','Менеджер маркетплейсов'),('ENGINEER','Технический специалист'),('STOCK','Сотрудник склада'),('DESIGNER','Дизайнер'),('ADMIN','Администратор');",'COMMIT;','-- Проверки готовности, принадлежности версии и RBAC выполняются сервисом в транзакции.','-- DDL не устанавливает роли ОС/СУБД и не подменяет миграции рабочего приложения.']
(DB/'schema.sql').write_text('\n\n'.join(ddl)+'\n',encoding='utf-8')
(DB/'model.json').write_text(json.dumps(dict(tables=tables,indexes=indexes),ensure_ascii=False,indent=2),encoding='utf-8')
if __name__=='__main__':print(len(tables),'tables',sum(len(t['columns']) for t in tables),'columns')
